### PR TITLE
Require a leading slash for paths relative to the root

### PR DESCRIPTION
**Pull request by snoack**
Originally filed by @jonafato:

> The [`glob` module](https://docs.python.org/3/library/glob.html#glob.glob) support recursive wildcards. Support for this would be really useful to ignore specific types of errors, e.g. to ignore unused imports in `__init__.py` files. An example would look something like this:
> 
> ```cfg
> # setup.cfg
> [flake8]
> per-file-ignores = 
>     **/__init__.py: F401
> ```
> 
> Would you be open to adding this feature? If so, I can try to implement it in a PR.

### CODE REVIEW

**Comment by snoack** [comment]
We cannot use the `glob` module but have to use `fnmatch` for reasons outlined in https://github.com/snoack/flake8-per-file-ignores/issues/1#issuecomment-335046937. Therefore `*` matches already across directory boundaries, as explained [here](https://stackoverflow.com/questions/18341848/fnmatch-and-recursive-path-match-with#answer-18341937). That means `*/__init__.py` matches `a/__init__.py` and `a/b/__init__.py` but not `__init__.py` (on the top-level). Admittedly, these semantics are kinda confusing, impractical and inconsistent, but I'm not going to implement my own glob pattern parser.

Anyway, in order to match files with the same (or similar) name, regardless of their location, hindsight, it might have been a better idea to require an explicit leading `/` to indicate a path relative to the root (like in `.gitignore`). However, at the current point this would be a slightly breaking change.

@kvas-it and @The-Compiler, what do you think?

**Comment by The-Compiler** [comment]
> Anyway, in order to match files with the same (or similar) name, regardless of their location, hindsight, it might have been a better idea to require an explicit leading / to indicate a path relative to the root 

i.e. `/__init__py` would only match in the root, while `__init__.py` would match that file anywhere? Seems like a good idea to me.

> However, at the current point this would be a slightly breaking change.

Seems fine to me to have a breaking change and release a v1.0 after that.

**Comment by kvas-it** [comment]
I think that the change is an improvement. Not sure if it's worth breaking backwards compatibility but if it's a new major version, as @The-Compiler suggests, it seems ok.

**Comment by snoack** [comment]
> i.e. `/__init__py` would only match in the root, while `__init__.py` would match that file anywhere?

Exactly.

> Seems like a good idea to me.

> I think that the change is an improvement.

Awesome! So it seems everybody agrees to my suggestion. So I wrote a patch, created a branch and turned this issue into a pull request. Feel free to review the changes and/or try out my branch. I want to make sure that I got it right before releasing this, since I would like to avoid another breaking change.

> Seems fine to me to have a breaking change and release a v1.0 after that.

> Not sure if it's worth breaking backwards compatibility but if it's a new major version [...] it seems ok.

I'm not sure if the next release should be 1.0 because of this change. The move from 0.* to 1.0 would indicate the first stable release, which would be a separate topic. On the other hand, I think it is fair to expect some small degree of breaking changes while in early development stages as indicated by a version of 0.*. FWIW, flake8 itself had larger breaking changes within the same stable major version in the past.

As for the breaking impact of this change, it doesn't seem to be too severe after all. If you didn't use leading slashes yet, nothing will stop being ignored after this change. Only in corner cases, like when you configured ignores for a script on the top-level, and a script with the same name exists somewhere down the tree, this will cause the same ignores being applied to the latter as well. The other way around, if you use leading slashes, there is no difference at all between 0.4 and after this change landed.

**Comment by kvas-it** [comment]
I looked at the proposed code and it looks good to me. I also agree that it doesn't have to be a release 1.0 just because of this. Releasing this as 0.5 seems perfectly reasonable.

**Comment by snoack** [comment]
Thanks! I have merged this patch and released version 0.5.

**Comment by jonafato** [comment]
Thanks for the quick feature addition!

**Comment by snoack** [comment]
As of version 0.6, I switched to [pathmatch](https://github.com/demurgos/py-pathmatch) (e4dd145), in order to prevent `*` and `?` from matching the path separator. Another side effect is that recursive glob patterns (i.e. `**`) are supported as well, now.

**Pull request merged**
